trigger:
  - '*'
  
variables:
  buildConfiguration: 'Release'

schedules:
    - cron: '0 3 * * *'
      displayName: 'Deploy every day at 3 A.M.'
      branches:
        include:
        - main
      always: false 
  
stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs: 
    - job: 'Build'
      displayName: 'Build job'
      pool:
        vmImage: 'ubuntu-20.04'
        demands:
        - npm
  
      variables:
        wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
        dotnetSdkVersion: '5.x'
  
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET SDK $(dotnetSdkVersion)'
        inputs:
          version: '$(dotnetSdkVersion)'
  
      # - task: Npm@1
      #   displayName: 'Run npm install'
      #   inputs:
      #     verbose: false
  
      # - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      #   displayName: 'Compile Sass assets'
  
      # - task: gulp@1
      #   displayName: 'Run gulp tasks'
  
      - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
        displayName: 'Write build info'
        workingDirectory: $(wwwrootDir)
  
      - task: DotNetCoreCLI@2
        displayName: 'Restore project dependencies'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
  
      - task: DotNetCoreCLI@2
        displayName: 'Build the project - $(buildConfiguration)'
        inputs:
          command: 'build'
          arguments: '--no-restore --configuration $(buildConfiguration)'
          projects: '**/*.csproj'
  
      - task: DotNetCoreCLI@2
        displayName: 'Publish the project - $(buildConfiguration)'
        inputs:
          command: 'publish'
          projects: '**/*.csproj'
          publishWebProjects: false
          arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
          zipAfterPublish: true
  
      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: drop
  
  - stage: 'Dev'
    displayName: 'Dev-env. deploy'
    dependsOn: Build
    jobs:
    - deployment: Deploy
      pool:
        vmImage: 'ubuntu-20.04'
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop

            - task: AzureWebApp@1
              displayName: 'Azure App Service Deploy: website'
              inputs:
                azureSubscription: 'sc-deploy-tailspin-space-game'
                appName: 'lp-myweb-dev'
                package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
            
              
  - stage: 'Test'
    displayName: 'Test-env. deploy'
    dependsOn: Dev
    #condition: eq(variables['Build.Reason'], 'Schedule')
    jobs:
    - deployment: Deploy
      pool:
        vmImage: 'ubuntu-20.04'
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop

               
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'sc-deploy-tailspin-space-game'
                appType: 'webAppLinux'
                appName: 'lp-myweb-dev'
                package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
                runtimeStack: 'DOTNETCORE|5.0'

  - stage: 'Staging'
    displayName: 'Staging-env. deploy'
    dependsOn: Test
    jobs:
    - deployment: Deploy
      pool:
        vmImage: 'ubuntu-20.04'
      environment: staging
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop

            - task: AzureWebApp@1
              displayName: 'Azure App Service Deploy: website'
              inputs:
                azureSubscription: 'sc-deploy-tailspin-space-game'
                appName: 'lp-myweb-stg'
                package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'  